[toolchain]
channel = "stable"
components = ["rustfmt", "clippy", "rust-src"]
targets = [
  "wasm32-unknown-unknown",
  "aarch64-linux-android",
  "armv7-linux-androideabi",
  "x86_64-linux-android",
  "i686-linux-android",
]
profile = "minimal"
