name = "takusu"
main = "build/worker/shim.mjs"
compatibility_date = "2025-01-01"

[build]
command = "worker-build --release"

[[d1_databases]]
binding = "DB"
database_name = "takusu"
database_id = "00000000-0000-0000-0000-000000000000"
migrations_dir = "migrations"

[vars]
TAKUSU_LOG = "info"
# TAKUSU_ALLOWED_ORIGIN = "https://my-app.example.com https://other.example.com"
