name = "takusu"
main = "build/worker/shim.mjs"
compatibility_date = "2026-06-16"

[build]
command = "worker-build --release"

[[d1_databases]]
binding = "DB"
database_name = "takusu"
database_id = "cd59bcb7-e766-4edf-8baa-7fc403f1e86f"
migrations_dir = "migrations"

[vars]
TAKUSU_LOG = "info"
# TAKUSU_ALLOWED_ORIGIN = "https://my-app.example.com https://other.example.com"

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true
