name: Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yaml'
      - 'flake.nix'
      - 'flake.lock'
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@02a151ada4993995686f9ed4f1be7cfbb229e56f
        with:
          extra_nix_config: |
            keep-outputs = true
            keep-env-derivations = true

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-docs-${{ hashFiles('flake.lock', 'flake.nix') }}
          restore-prefixes-first-match: |
            nix-${{ runner.os }}-${{ runner.arch }}-docs-
          gc-max-store-size-linux: 2G
          purge: true
          purge-prefixes: |
            nix-${{ runner.os }}-${{ runner.arch }}-docs-
          purge-last-accessed: P6D
          purge-primary-key: never

      - name: Build docs
        run: nix shell .#ci-docs -c mdbook build docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/book

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
